### ISSUE TITLE
Add Payment with Balance on M+ Form

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/Icecrown-Precious-Bot-Public#10]
![image](https://user-images.githubusercontent.com/77668716/106907916-0ca89300-66ff-11eb-86a9-cf553e4a5ce7.png)

Maybe allow to write Balance

or add a tickbox where you also have to add discord tagg of the person whos balance will be taken

![image](https://user-images.githubusercontent.com/77668716/106908375-8c366200-66ff-11eb-9e27-1ee9c1172629.png)

**Comment by Efthymios-Papakostopoulos** [comment]
This is resolved with the new bot.

When it comes for advertisers to be able to insert discord, its declined for security issues.
