### ISSUE TITLE
Wording change request for !logs

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#100]
There is clearly some misunderstanding of the term "movements" (even though the log itself displays this info).

Requesting update to body text of !logs response from:

> Download the HTML file above and open it in your browser (Chrome, Firefox...)
> 
> Make sure the below information regarding your payment information is correct.

**To:**

> Download the HTML file above and open it in your browser (Chrome, Firefox...)
> 
> Make sure the below information regarding your payment information is correct. "Movements" are balances moved from previous cycles, in-house payments, casino actions, strikes etc; all actions taken towards your balance.

![image](https://user-images.githubusercontent.com/43845551/131223579-bcef290f-f213-4658-91a1-95bed7b221ee.png)

**Comment by iElsha** [comment]
Can you give me an exact new wording please

**Comment by Tueri** [comment]
Updated original - didn't split the quotes:

> Download the HTML file above and open it in your browser (Chrome, Firefox...)
>
> Make sure the below information regarding your payment information is correct. "Movements" are balances moved from previous cycles, in-house payments, casino actions, strikes etc; all actions taken towards your balance.
