### ISSUE TITLE
Show "Previous Balance" when using !b

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#103]
I have had some feedback and suggestions from the boosters that a "previous balance" is available to them in other communities, so when cycles change or similar, they are always on top of their earnings.

At the moment only current is available, so when switching cycles the old balance is unknown unless fetching it from logs.

It's important that this not come as a seperate command like !b archived or !logs archived as it is now, since the boosters cannot get used to our split request compared to others' single request.

Tll;dr = !b should return **both** current and previous balances from the same request.

**Comment by iElsha** [comment]
Will slightly increase latency but should be good, worst case scenario we'll create a cache

**Comment by Tueri** [comment]
This is done, closing.
