### ISSUE TITLE
Add Boosting Faction

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/Icecrown-Precious-Bot-Public#11]
Currently We only have "Faction Recieved:" (Where we got the gold)
![image](https://user-images.githubusercontent.com/77668716/106908847-f818ca80-66ff-11eb-963e-45912577184c.png)

But often we get a payment on the opposite faction, and then we still have to choose the faction of the boost instead of the payment, so the correct boosters can sign up.

Therefor, please add Boosting Faction: 
![image](https://user-images.githubusercontent.com/77668716/106909331-79705d00-6700-11eb-8874-d0655e2c2e38.png)

**Comment by Efthymios-Papakostopoulos** [comment]
Resolved with the new bot.

![image](https://user-images.githubusercontent.com/77063189/121648211-effedc00-ca9f-11eb-9031-be0ad99fe149.png)
