### ISSUE TITLE
Make M+ channels visible through the journey.

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#111]
Title.
Boosters need to see we are active, so having the M+ channels visible while locked will at least show that - because the runs disappear, although intuitive, it demotivates others who think there are no runs.

Permissions;
H/A Mythic+ View Channel, Read Message History, Deny add reactions, Deny Send Messages.

**Comment by Efthymios-Papakostopoulos** [comment]
I believe this a really good idea just for the fact typed above that newcomers can't see channels and they believe we don't have runs going. 👍

**Comment by Tueri** [comment]
This is implemented now, last change is to hide the **completed** category from view - only the boosters and adv who participated should see it to avoid bait pings.

**Comment by Bgabor997** [comment]
implemented and deployed 2021.10.14
