### ISSUE TITLE
Ticket rotation glitch when customer deletes a ticket during assignment

### ISSUE THREAD

**Issue by iElsha** [Icecrown-Community/Icecrown-Precious-Bot-Public#114]
When the customer deletes a ticket while precious tries to match someone, it doesn't take it into account and loop through all of them (limit of 5)

**Comment by Suzaru** [comment]
Also potentially related:

- Customer opens a ticket
- Next advertiser in line gets the DM
- Customer deletes ticket before advertiser claims
- turn lost, no restoration 

This seems to be not restored either. It should be.

**Comment by Bgabor997** [comment]
The ticket deletion thing is solved
