### ISSUE TITLE
Adding a note using submit includes booster tags too

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#15]
Example note:
<@131385820153118720> <@280343689774235649> <@168785990691848193> <@291328631458758666> <@231142884252975105> <@278229777804951552> <@286149224129626113> teleengc
When the only thing left at the end was:
teleengc

Just clogging up note space :)

**Comment by iElsha** [comment]
@Tueri keep me updated if the current patch doesn't fix the issue but it should

**Comment by iElsha** [comment]
@Tueri if this is fixed, please close, otherwise ping me
