### ISSUE TITLE
Advertisers who also boost a run are named 3 times in the submit

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#16]
Typically, this ends up with the advertiser in the correct slot, then mentioned twice as a booster, meaning their name appears 3 times in the submit, skewing the balance results.

**Comment by iElsha** [comment]
Adding this to #12 & duplicate as the issue is the same in fact

**Comment by iElsha** [comment]
https://discord.com/channels/608866658114863104/756552333533511801/810500942993686528

**Comment by iElsha** [comment]
@Tueri is that fixed, if so, please close
