### ISSUE TITLE
Split channels for different armor types

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#17]
Horde-boost-announcement is being flooded, Tuesday's are not attractive to advertisers to manage due to boosts disappearing and needing to be posted 2 or 3 times before being seen.

**Example:**
#🔴general-announce
#🔴cloth-announce
#🔴mail-announce
#🔴leather-announce
#🔴plate-announce

#get/claim-roles dictating by armor type which channels can be seen. Issue #5 related and probably should be done before so that tanks aren't further forced to have additional steps or see additional info.

**Comment by iElsha** [comment]
![image](https://user-images.githubusercontent.com/38140638/107656838-d762ee80-6c84-11eb-917b-73b0518cd35d.png)
We'll need to split mythic+ into mythic+ horde & alliance for it.

**Comment by Efthymios-Papakostopoulos** [comment]
That being said we need at least 8 more channels which isn't ideal. What if we just split them into:

`Rare Channel A`
`Epic Channel A`

`Rare Channel H`
`Epic Channel H`

By that we will get less spam and more organised channels. We can give that a go and if it doesn't work we move into Tueri's first suggestion
