### ISSUE TITLE
Deduct command for Epic & Above advertisers.

### ISSUE THREAD

**Issue by Efthymios-Papakostopoulos** [Icecrown-Community/Icecrown-Precious-Bot-Public#18]
As per title says Deduct command for in-house purchases.

The process has to be as:

1)Advertiser press the command
2)Booster agrees via a bot message
3)The actual deduction happens.

This will potentially save time from everyone and an actual proof of boosters having that balance.

**Comment by iElsha** [comment]
Have you check `!submitb`
![image](https://user-images.githubusercontent.com/38140638/107653809-53a80280-6c82-11eb-9a6b-7dd1d4ade07c.png)

**Comment by Efthymios-Papakostopoulos** [comment]
That is for after the boost is being completed. I am more referring to raid purchases & payments before hand. 😉

**Comment by iElsha** [comment]
We have `!ihp`
![image](https://user-images.githubusercontent.com/38140638/107745415-93b7c580-6d14-11eb-9b37-89b7027709b7.png)

**Comment by Efthymios-Papakostopoulos** [comment]
This is only for Admins. I am suggesting one for Advertisers. More specifically Epic & Above.

**Comment by iElsha** [comment]
No, there's a security risk which would be too high
