### ISSUE TITLE
[QoL]Adding Bankname-realm to Bot Output for Gold Collecting.

### ISSUE THREAD

**Issue by ghost** [Icecrown-Community/Icecrown-Precious-Bot-Public#19]
Current Example of message posted to advertiser which is then copy pasted to the gold collector

RunId: 808878720394854450
Pot: 375,000
Activity: Dungeon M+
ActivityId: 0
Advertiser: Jamésdruid-Tarrenmill [Trainer]
AdvertiserId: 183286897823449088
Realm: doomhammer

Suggestion would be that it now does

RunId: 808878720394854450
Pot: 375,000
Activity: Dungeon M+
ActivityId: 0
Advertiser: Jamésdruid-Tarrenmill [Trainer]
AdvertiserId: 183286897823449088
Realm: doomhammer

**Bank : Bankname-realm**  E.g. Iccbh-Doomhammer

This new message is automatically generated by the bot based on the realm the gold was collected on to save the GC having to reference the sheet each time. Ensuring it's on a separate line as well so it's not copy pasted into the ingame mail.

This will also reduce errors on the user end as it's defined by the bot. Plus we get to copy paste it!

**Comment by iElsha** [comment]
I think there is a WA available at the moment but I agree with the idea.

**Comment by Dejnaa** [comment]
I think this is not needed anymore with our amazing ICC Addon?

**Comment by Dejnaa** [comment]
Can someone close this post?
