### ISSUE TITLE
Discord Embed Bot.

### ISSUE THREAD

**Issue by Efthymios-Papakostopoulos** [Icecrown-Community/Icecrown-Precious-Bot-Public#2]
**What we want:**

We want a discord embed bot that comes together with an Admin panel where we can edit prices & information in our public posts.

1. PvE Prices
2. PvP Prices
3. Any other Public post we have.

**Why we want that?:**
At the moment we have to delete & repost in case of an edit. Things are getting scuffed, customers see previous prices, miss-allingemnts and much more.

**Comment by iElsha** [comment]
Planned internally but won't be available until March.

Anything we can do in the meantime for it, like improving the way you edit the prices & information with a better text editor?

**Comment by iElsha** [comment]
The solution I have in mind is using a database like Firestore where you would have access to a Price categories.

Inside this one you can create new documents (aka embed) with fields inside, we'll need to work on the structures for it but might be possible. You can find more information here https://firebase.google.com/docs/firestore/data-model

A bot command like `!updatePriceList` might do the work in the meantime

**Comment by Efthymios-Papakostopoulos** [comment]
> Planned internally but won't be available until March.
> 
> Anything we can do in the meantime for it, like improving the way you edit the prices & information with a better text editor?

Not really as we use [How we edit At the moment](https://discohook.org/) and it looks like that.

![image](https://user-images.githubusercontent.com/77063189/105326249-37aac700-5bd6-11eb-9660-e7595236dc7f.png)





> The solution I have in mind is using a database like Firestore where you would have access to a Price categories.
> 
> Inside this one you can create new documents (aka embed) with fields inside, we'll need to work on the structures for it but might be possible. You can find more information here https://firebase.google.com/docs/firestore/data-model
> 
> A bot command like `!updatePriceList` might do the work in the meantime

Is it something i can do myself? I saw it has some coding inside.

**Comment by iElsha** [comment]
There won't be any coding needed for you however, there won't be any preview.

I still need to think about it as it's a tough subject that I'm trying to solve (thinking about) since a few months already with an easy solution for me and for you due to the lack of time
