### ISSUE TITLE
Mention the same booster twice in submit function

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#20]
Admittedly this was asked about when building the fucntion, but we do actually need boosters to be able to be mentioned multiple times for the submit function on discord (and form I imagine?).

**Comment by iElsha** [comment]
Why do you need to mention the same booster twice?

**Comment by Tueri** [comment]
Mostly for back-filling, teams finding an additional member outside of the community to fill a stacked run, similiarly in raids, or splitting cuts in special ways etc.

**Comment by iElsha** [comment]
I won't say it truly changes the way how I detect boosters but it changes it at 80%+.

What's the priority here?

**Comment by Tueri** [comment]
It's a rare occasion, I probably have to patch it up once or twice per week. If it's not something that's an easy fix then we can add it to processes and guides that if (for any reason) a booster needs 2x, 3x etc the cut for the run, they are to open a ticket and let us know.

**Comment by iElsha** [comment]
Will be available with new precious
