### ISSUE TITLE
Advertiser Trainer-Precious🎀 needs to mimic the new features of Precious🎀

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#25]
Title :)

**Comment by iElsha** [comment]
Really?

**Comment by Tueri** [comment]
A solution for this could be a slider on the M+ form, that when used it sends to the training zone instead with permissions for adv trainers/managers and the trainee who posted it. State changes don't need to move the post anywhere and the submit function would delete the run instead. This would theoretically be available for non-trainees to use if they wanted to test some outputs before posting when unsure on something, if the permissions are as above. 
![test](https://user-images.githubusercontent.com/43845551/123544945-a1af3580-d74d-11eb-9260-07baabde23a6.png)

**Comment by iElsha** [comment]
duplicate
