### ISSUE TITLE
Busy hours/Traffic times management suggestion

### ISSUE THREAD

**Issue by Elainfeaine** [Icecrown-Community/Icecrown-Precious-Bot-Public#28]
Gooood morning everyone! ^^
With the new Precious changes some people (and believe me, its not just me! :P) seem upset about 'camping' different channels to sign up for the boosts. Its mainly about people who put effort into gearing up more than one armor type, lets say 2, who now are required to be able to jump between 3 channels to sign up for boosts. With no bot delay depending on channel, person who lets say has 2 different armor types actually has LESS chance to sign up for a boost (I obv mean as getting picked for the boost), than person with one armor only. Why? (lets say boosts came in order at the same time: leather stack>no armor stack>cloth). Because if they arent quick enough to sign up for boost that showed up first (leather in this situation) there is very little possibility they will be first one to sign up for no armor stack, as bots reaction will show at the same time. As much as I understand different channels are perfect for busy times, as its simply a nightmare to fill the funs when bot posting 3+ orders at the same time; some runs are getting 'forgotten' and  advertisers need to either repost, or spam link for unfilled boosts. Separate armor types channels will work PERFECT in these times/situations, (bravo for idea, because its very good <3), but when its not so busy, it will simply build a frustration in boosters.
So I came with couple of ideas on how to resolve this problem and I wonder how complicated would it be or if even possible to be done for our perfect developers <3 Ok, lets see what you think.
(Im sorry Elsha, I know Precious is 200IQ) Would it be possible to create 'smart bot'  who recognizes busy times? Either automatic which would jump into one of the modes Im about to suggest or manual that would inform member of the management that its busy and its time to jump into one of the modes. (I said 'create' even tho its probably better to call it adding function or something, sorry, not an IT person ;p)
So lets say we go back to our old method of posting boosts via 'horde announcer channel' - one channel for all the boosts, armor types etc. And then boom, it gets busy! Precious recognizes traffic and jumps into:
1st mode
'oh, im so busy'
Random day, lots of advertisers spamming their macro, they dont have time to look if other advertisers run got filled yet. But precious knows! because she knows 3+ boosts at the same time mean confusion and struggle to fill! She recognizes 'oh, im so busy' mode criteria are met and instead of posting to Horde announcer channel, she posts to different armor types. Before she does that tho, she automatically posts announcer for booster that she enters 'oh, im so busy' mode and will start posting to armor type channels instead of horde announcer channel. 
I just didnt find example of criteria to be met to get her to switch back to 'Im Precious' aka 'Oh, Im not busy anymore' to resume using Horde Announcer Channel only. Timer perhaps?

2nd mode
'traffic hour!'
Instead of recognizing if its busy or not, we simply put Precious on Horde Announcer Channel (all armor types) through the day, and then at lets say 4(5?)pm when it actually gets busy for boosts, she either automatically switches to Armor Type channels or we get Management to click some big precious button to get her switch to armor types channels.

As much as I understand all the hard work put into Precious and whole new armor type channels system, steps taken for the betterment of the community. Being a TANK who jumps between all of these channels *Non armor-Cloth-Mail-Leather/Plate* (so every tank has 4 channels to camp, as they are all either plate or leather) is definitely going to be extremally frustrating. And saying they all have same chance, or its rng or luck is simply a lie, because it will all depend on latency and on how fast can our pc (not even us) react that you clicked to switch a channel. And thats because all 3 boosts I mentioned in the beginning will post at the same time with reactions showing up at the same time. People with shittier internet/pc had this perfect chance to sign up when 2/3 boosts were coming through because they could get sort of more prepared to click reactions as on 2nd/3rd posted boosts these reactions were NOT showing up immediately ^^

Soooo... What do you think? :D

**Comment by Wanhedaa** [comment]
> Its mainly about people who put effort into gearing up more than one armor type, lets say 2, who now are required to be able to jump between 3 channels to sign up for boosts. With no bot delay depening on channel, person who lets say has 2 different armor types actually has LESS chance to sign up for a boost

If its not a separated channel, it would be the same. You dont have to camp any of those channels. If you camp the discord, you get the notification and ping like 3 seconds before the reactions appear. If you want to sign up for 3 boost at the same time, that means, you do **_multi sign_**, and its strikeable (wasting the advertiser's time).

If you really want to be quick, turn your discord status to online, make the discord notifications show on the screen while ingame, and you just have to instant click on the message, which means, you will have still 2 seconds, until the reactions appears.

Honestly i like this system.

**Comment by Elainfeaine** [comment]
When you mentioned multisigning, this is not what i meant at all. I didnt say someone wants to sign up for 3 boosts and boost them all. Im saying if you are LATE for the 1st one, it means you wont be able to be quick enough for 2nd or 3rd one either because reactions start at the same time. This is situation i personally may have when plate and non armor come at the same time. I can 'camp' plate channel, when boost there and in non-armor will come at the same time. And if im too late for plate stack click because someone is simply quicker, do you think I will have ANY chances to switch channel, move mouse over to reaction and click it before someone else does? No way. And as much as I understand its not for MY BALANCE, there are other people there saying the same thing.
When boosts were posted in 1 channel, 2nd order would have even bigger delay for people to sign up, giving more people chance to click it and success.

**Comment by Tueri** [comment]
#36 covers a solution for this that will be a better way of handling the boosts, we won't ever support "campers" anyways 😄
