### ISSUE TITLE
Add booster cut and number of runs to DM message when a run is locked.

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#29]
Klexe-Blackrock suggested this, as it also allows boosters to better keep track of their own runs beyond the log file. 👍🏼

**Comment by iElsha** [comment]
Add it to the completed boost message

**Comment by Dejnaa** [comment]
Has this been done? Seems like a rather fast adjustment to what the bot sends to the booster since all info is already in the booking.

**Comment by Dejnaa** [comment]
@Bgabor997 how long would it take to make this? The cut is already shown by the bot, so shouldnt be much work to put it into the bot message?
