### ISSUE TITLE
Remove the word "Warning" from 🧻bot-logs

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#32]
The entire wording in the first line can be removed: 

WARNING : Mythic Plus Announcement
Incorrect role
You don't have the permission to signs up as healer in a M+12.

to:

Incorrect role
You don't have the permission to signs up as healer in a M+12.

---
Mostly because people are seeing this as some sort of punishment, and if we do move to a warning system with strikes, this can't exist.

**Comment by Dejnaa** [comment]
Has this been implemented? Seems like a message edit is needed and no coding/changing of the program itself
