### ISSUE TITLE
Server not shown - add it to GC warning message

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/Icecrown-Precious-Bot-Public#33]
Heya,

when things have changed in Precious (e.g. boosters are notified by a message in the message who to whisper to), the "realm paid" option also disappeared from the public bot message.
![image](https://user-images.githubusercontent.com/77633500/107980699-02b94680-6fc1-11eb-9960-5950769a64c0.png)
This note was important / usefull for the gold collectors, because sometimes IDs get mixed up, we can't find them, and collection would also be faster. We would prevent the “on which realm have the gold” question by saying that we are already there and waiting for the group to start.

At least I found this feature useful, I don't know of any other gold collector what do think about it.
![image](https://user-images.githubusercontent.com/77633500/107981002-95f27c00-6fc1-11eb-8870-6f26bbedf695.png)

**Comment by Efthymios-Papakostopoulos** [comment]
The `Realm paid` & `Character to whisper` are gone due to privacy issues with advertisers and they're not coming back.

There is the BOT message when boost is done which can't mix up things. Also you as `Gold Collector` have a spreadsheet were you can note things down as well.

I can only suggest editing the message on the warning channel @iElsha and include it there.

**Comment by Wanhedaa** [comment]
> The `Realm paid` & `Character to whisper` are gone due to privacy issues with advertisers and they're not coming back.
> 
> There is the BOT message when boost is done which can't mix up things. Also you as `Gold Collector` have a spreadsheet were you can note things down as well.
> 
> I can only suggest editing the message on the warning channel @iElsha and include it there.

the message edit is fine too. And yes we have sheet, we have everything, but anything can happen :D But okay, yeah, updating the message in the `Warning channel` would be great

**Comment by iElsha** [comment]
#60 will fix it
