### ISSUE TITLE
"Warning" option for #🎳strikes 

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#34]
We need a way to punish without moving straight to strikes or scrolling DMs. It can literally be an Echo like current strikes but with no action on DB. There are fancy things possible here, but are simply not needed because we can just run a discord search against the channel to see if someone has been strriked before.

**Comment by IndigoICC** [comment]
This will without a doubt be a better way of dealing with the "minor" mistakes that occur during any given boost. Like Tueri said; it will be such a big time saver for when we do research outside of the ticket that is opened.

**Comment by iElsha** [comment]
like strike for 0 that doesn't log in database but put a msg in the channel?

**Comment by IndigoICC** [comment]
Aye - Command could be !warning <Reason>.

**Comment by Papa2324** [comment]
> 
> 
> like strike for 0 that doesn't log in database but put a msg in the channel?

Doesnt necessarily have to not log it in database. Would be pog if it can be added as just "warning" in the "comment" section that's just there permanently, that way we can see everyone's warning history clearly rather than "hey i think we warned this guy before?"

**Comment by Tueri** [comment]
That is ideal, but was thinking for something easy for dev side for a more immediate solution, but if !strike 0 works for now we can use that until a better solution is here - logging on the db would be nice for sure.
