### ISSUE TITLE
📌README: Migrating Precious code base

### ISSUE THREAD

**Issue by iElsha** [Icecrown-Community/Icecrown-Precious-Bot-Public#36]
@Precious will slowly see its code base totally reworked for multiple reasons. Therefore, every opened request will not be fixed until this is done, except for bugs and fixes.

The progress can be followed here https://github.com/Icecrown-Community/Icecrown-Precious-Bot-Public/projects/1

**Comment by iElsha** [comment]
This is a preview of the new M+ system that takes into account all feedbacks and discussions we had since the last few months.

https://user-images.githubusercontent.com/38140638/117954233-1dc4f980-b317-11eb-9b81-2a4d8dba8b58.mp4

**Comment by iElsha** [comment]
- When Locking the boost you receive the voice channel DM
<img width="536" alt="image" src="https://user-images.githubusercontent.com/38140638/120081208-b2bc4680-c0bc-11eb-9210-7d0921b11b52.png">

- When click on the success ✅ fail icon ❌  before a certain amount of time (10 minutes after the boost has been lock) You get a nice DM
<img width="385" alt="image" src="https://user-images.githubusercontent.com/38140638/120081183-81437b00-c0bc-11eb-941f-19ce3fd42218.png">

- Opening back the boost doesn't trigger any DM

- Cancelling the boost sends you some information
<img width="467" alt="image" src="https://user-images.githubusercontent.com/38140638/120081196-a20bd080-c0bc-11eb-84ac-e675becefc3e.png">

-  Clicking on the ❌ as booster to notify the advertiser and boosters of a failure 
    - Advertiser view
<img width="480" alt="image" src="https://user-images.githubusercontent.com/38140638/120082846-7f31ea00-c0c5-11eb-83b4-ec619ae7bd36.png">
    - Booster view
<img width="470" alt="image" src="https://user-images.githubusercontent.com/38140638/120081290-4261f500-c0bd-11eb-8d36-d60ae092aeb3.png">

- Clicking the ✅ as a booster notify the advertiser and boosters of a succes
      - Advertiser
<img width="481" alt="image" src="https://user-images.githubusercontent.com/38140638/120081562-8a354c00-c0be-11eb-962f-ca94a3a37662.png">

      - Booster
<img width="394" alt="image" src="https://user-images.githubusercontent.com/38140638/120081554-81447a80-c0be-11eb-88d1-e42f32a98b27.png">

On top of that the channel receives a circle 🔴 or 🟢 to its name based on the boost completion status
<img width="232" alt="image" src="https://user-images.githubusercontent.com/38140638/120081641-ea2bf280-c0be-11eb-9d7c-97bacfda05e4.png">

---

More coming soon, stay tuned ™️

**Comment by Wanhedaa** [comment]
For the first part 

> When Locking the boost you receive the voice channel DM

Can we have a link with the runid as we had before, so the boosters can find the post with clicking on the RunID easier to press "check" on it? Especially on tuesdays we have a lot overflooding boosts, sometimes they don't even bother finding the boost and the advertiser doesn't get notified about it being done.

**Comment by iElsha** [comment]
Right I forgot thx for LMK.
However thanks to the new posting system that should fix the Tuesday fever.

**Comment by iElsha** [comment]
**Depleted run**
- DM adv only
<img width="524" alt="image" src="https://user-images.githubusercontent.com/38140638/120096731-6c530000-c12d-11eb-91da-5335a37f96d6.png">

*Note for management: A msg is still sent to the boost depleto channel*

**Success run**
- Adv - you get as much mail log embeds than you added payment option
For instance I put both draenor & hyjal as payment
<img width="517" alt="image" src="https://user-images.githubusercontent.com/38140638/120097393-7fb39a80-c130-11eb-949f-4c7bda0d01b4.png">

- Booster
You get a simple notification, but the runId link is not working though (channel gets deleted)
<img width="383" alt="image" src="https://user-images.githubusercontent.com/38140638/120097418-a07bf000-c130-11eb-96f6-1cda5e25daf7.png">

**Comment by Tueri** [comment]
Looks great both sides, even if the link doesn't work for the ID, it's perfect for personal logging. Have you considered how the additional boost IDs (for multi-realm payments would affect the booster/adv competitions?

**Comment by iElsha** [comment]
Alright, cool!

I already handled the booster competition possible changes.
However, the adv are not yet done as the formula takes into account the number of row presents as a run count, I'll need to change this I guess

**Comment by iElsha** [comment]
Added reminder feature for run handling
<img width="561" alt="image" src="https://user-images.githubusercontent.com/38140638/120101780-088a0080-c148-11eb-81e0-fa8e99a24859.png">

**Comment by Tueri** [comment]
Can we reduce the time given for "run left open"? Should really not be open for more than 30 mins in our worst times, so 1 hour is enough.

**Comment by iElsha** [comment]
Sure, but what happen with future PvP boosts?
I guess I'll put a custom cooldown for them

**Comment by Tueri** [comment]
Yeah, or just none since they are within tickets, and the ticket is likely to be closed before the run is closed if it was left open with no claim.

**Comment by iElsha** [comment]
I'll worry about it later, this should not be a big change

**Comment by iElsha** [comment]
https://github.com/iElsha/Icecrown-Precious/pull/53

The old precious will be removed before 9.1
