### ISSUE TITLE
remove the "no key option" from the google doc

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/Icecrown-Precious-Bot-Public#38]
We have both options - **no specific key and random key** 
![image](https://user-images.githubusercontent.com/77633500/108594641-7cfc1900-737b-11eb-8ec1-bea0c6963a06.png)

I think we should remove the _no specific key_ option.

Reason: If its a random key, we still need a key to deplete.

Many times we are in case we need a random dungeon of (for example) 14, the boosters check in, but no one is willing to downgrade the key. If we choose the _**random key**_, the keystone icon will appear, letting us know that there is someone who will downgrade the key and not wait for the buyer to see what happens now because no one is sacrificing their key.

If someone clicks on the keystone icon just to get prio, and not willing to downgrade the key, should be a strike reason.

**Comment by DruidEmmaNielsen** [comment]
I use "No Specific Key" if client has key.
