### ISSUE TITLE
Teams are able to fill 5 spots in a team take.

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#39]
![image](https://user-images.githubusercontent.com/43845551/108595237-ae261a80-7376-11eb-82b9-4531d2656194.png)

5 Members of the team pressed teamclaim, so it filled them all, and subsequently paid them all too.

Id for this one was: 812653618251169792.

**Comment by iElsha** [comment]
It paid them all on the same pot rigt?

**Comment by Tueri** [comment]
Correct

**Comment by iElsha** [comment]
Fixes in new update
