### ISSUE TITLE
Increase team claim cap

### ISSUE THREAD

**Issue by iElsha** [Icecrown-Community/Icecrown-Precious-Bot-Public#40]
From 2 to 4?
![image](https://user-images.githubusercontent.com/38140638/108631340-c9258700-7469-11eb-9a75-4fcab2057262.png)

**Comment by Tueri** [comment]
4 would be fine for now yeah

**Comment by Tueri** [comment]
Changing my mind slowly...I think just uncap it for now, and see how it goes. The advertisers are confident there are enough keys to make everyone happy, and the teams are demotivated in ICC because of the cap altogether.

**Comment by iElsha** [comment]
implement
