### ISSUE TITLE
Have all people able to advertise do !Pset and have a pseudo name removing the -realm of their name.

### ISSUE THREAD

**Issue by ghost** [Icecrown-Community/Icecrown-Precious-Bot-Public#43]
One of the problems I'm having whilst doing the mailing of gold is that You constantly see the name-realm of the advertiser straight above the customer. From time to time this has caught me off guard and resulted in a boo boo.

If we make them all have the Pseudo name like Sefildh has here for example, it would remove the opportunity for this to happen.

![image](https://user-images.githubusercontent.com/78853011/110319422-c51b6c80-8006-11eb-84cb-e47119d5a360.png)

Also means that if they all have [Adv] in their name it's easier to see them on Discord for customers etc.

Thoughts?

**Comment by iElsha** [comment]
Handling special pseudo is a bit a pain in the ass, I'd honestly don't do it as it could bring issues in the future

**Comment by iElsha** [comment]
Won't be implemented as special pseudos are only for staff members
