### ISSUE TITLE
Manually submitting to Aggra (Portuguese) comes out as 'Aggramar'

### ISSUE THREAD

**Issue by Teleena** [Icecrown-Community/Icecrown-Precious-Bot-Public#44]
Manually submitting a run for the portuguese server Aggra comes out through Precious as a run submitted to Aggramar.
![image](https://user-images.githubusercontent.com/80272732/110345323-ad82ba80-7feb-11eb-8032-818b684a1e0c.png)
![image](https://user-images.githubusercontent.com/80272732/110345349-b5daf580-7feb-11eb-91ae-12699b07f172.png)

**Comment by iElsha** [comment]
Put themselves on grim-batol for now but will fix one day

**Comment by Dejnaa** [comment]
Cant imagine this is something El sha has to do himself, maybe ask someone to look into how to fix it? 
Pretty sure if it was a more used realm it would have been fixed instantly.

**Comment by Dejnaa** [comment]
@Bgabor997 how long do you think this would take to fix?

**Comment by Tueri** [comment]
Pinned message in submit-horde and submit-alliance on how to submit correctly:

>Aggra payments need to be submitted as:
>Aggra(Português)
>With no spaces, to be recognised as Aggra instead of Aggramar.

If this is a suitable solution then this can be closed.

**Comment by iElsha** [comment]
Works for me, re-open the ticket if it's not fine for advertisers
