### ISSUE TITLE
Active advertisers can be lost between their m+ sales easily

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/Icecrown-Precious-Bot-Public#47]
Since we don't have the realm name, voice channel in the bot post, and we advertisers don't get any notifications about them, kinda hard to sort the depleted runs.

Once we have 6-7 runs ongoing at the same time, maybe from different servers, from different customers, and 1 of them is depleted, i have no idea in what channel should i go and ask wasup, i have no idea on which realm happend the thing unless i see the logs, but maybe that's already too late.

It just happend to me, they whispered me its a deplete, i couldn't find them on voice, because of 100+ online ppl, and when i got the logs,  i could find out the name and realm, the customer was already offline.

solution: Send some message with details to the advertisers after _closing_ a run.
Server name, voice channel would be nice.

**Comment by iElsha** [comment]
A payment info command will be released in the upcoming update to fix the issue

**Comment by iElsha** [comment]
#60

**Comment by iElsha** [comment]
@Wanhedaa closing it, reopen if you have any question/needs that are not answered about this issue
