### ISSUE TITLE
Allow Management the ability to close a boost with 🗑️ reaction.

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#48]
I'm aware we can !close_boost and delete, but visually closing instead of running the command and deleting the post can be awkward. This is a QoL change and very low priority, if even possible.

**Comment by Dejnaa** [comment]
Lets add to this the lock option, if for some reason the advertiser can not do it so thatmanagment can.

**Comment by iElsha** [comment]
@Icecrown-Community/icc-the-citadel @Icecrown-Community/icc-advertiser-manager 
**Manager**, and **advertiser manager** now have access to the following interaction (upcomming update):
- Remove a booster
- Cancel 
- Open
- lock 
- submit 
- mark as depleted
