### ISSUE TITLE
Migrate all GForm errors from 🧻bot-logs to 🧻adv-form-logs

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#49]
![image](https://user-images.githubusercontent.com/43845551/110707514-53534680-81f1-11eb-8e08-b956cf758d74.png)
Example image - incorrect realms still being posted to 🧻bot-logs, all of these errors can be posted in the 🧻adv-form-logs.

**Comment by iElsha** [comment]
This will be fixed with the coming update
