### ISSUE TITLE
Trainee Advertisers cannot submit runs with balance (!submitb)

### ISSUE THREAD

**Issue by Teleena** [Icecrown-Community/Icecrown-Precious-Bot-Public#53]
A trainee advertiser trying to submit a run paid with balance with the !submitb command errors out as the trainee not having permission to do so.
![image](https://user-images.githubusercontent.com/80272732/111394959-60ed4e00-8681-11eb-9979-5a7557af56d0.png)

**Comment by Wanhedaa** [comment]
bump.
