### ISSUE TITLE
Booser roles skipped

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#55]
![image](https://user-images.githubusercontent.com/43845551/111888678-9b831d80-89d6-11eb-9a50-463f23beedc9.png)
Example image - when Precious grants roles to new members where the player is eligible for "Epic" roles, the "Rare" role is not given. This is important to be given so they get pinged for low level boosts or for advertisers to find a wider variety of members to carry out a service.

**Comment by Wanhedaa** [comment]
This is still up and it's bad because the epics doesn't get pinged for lower keys.

**Comment by Tueri** [comment]
This is not an enhancement, it's likely a bug - Precious always gave rare roles before, so this was an occurrance from the last update,

**Comment by Tueri** [comment]
![image](https://user-images.githubusercontent.com/43845551/115626531-8a8b3c00-a2f5-11eb-88dc-e9ac25772fff.png)
Legendary even skips epic - 0 pings for this dude :) (fixed ofc, just an example).

**Comment by iElsha** [comment]
The ping will be global in the new update
