### ISSUE TITLE
Allow Advertiser Trainers to pull logs for their trainees(i.e. people with Trainee Advertiser role)

### ISSUE THREAD

**Issue by MartinPahnev** [Icecrown-Community/Icecrown-Precious-Bot-Public#57]
It would simplify our lives and reduce the hounding of the trainees from us(atleast me) - asking them daily on their sales, + it would also help us see what they are focusing on and do they need some form of suggestions/help.

Tueri said this option is available to admins, so I think we as Advertiser Trainers should get it in *nerfed* form.

**Comment by iElsha** [comment]
This will be present in the upcomming update
