### ISSUE TITLE
#advertiser-strike channel

### ISSUE THREAD

**Issue by IndigoICC** [Icecrown-Community/Icecrown-Precious-Bot-Public#58]
A complete replica of the current #strikes channel; but will solely be used for advertisers. 

New command; !strikea ID, amount, reason

**Comment by Dejnaa** [comment]
Is there any particular reason why they gotta be in a separate channel?
It gives more work for Elsha to set up, and people who want to have a laugh can just go to 1 channel instead of 2?

Let me know what you think :)

**Comment by iElsha** [comment]
@IndigoICC Do we need the extra channel?

**Comment by Tueri** [comment]
A middle-ground for this could be an alternative command (like "!strikea") and the embed from Precious reads "Advertiser Strike" instead of "Strike" and uses a different colour for the left margin, like the green we use for Trainees for example.

**Comment by IndigoICC** [comment]
Personally I like the differentiation of having two separate channels. I don't mind using the middle ground above, though.

**Comment by iElsha** [comment]
@Tueri needs to determine if we want middle-ground or new channel - no difference on tech side

**Comment by Dejnaa** [comment]
@Tueri Is this still in your hands or have it been put back in the pipeline?
