### ISSUE TITLE
Keyholders not prioretized over armorstack

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/Icecrown-Precious-Bot-Public#6]
Hello

Currently when you have chosen an armorstack, a booster without that armor cant be chosen even if he has the key.
We often have to allow keyholders to not follow the armor-request as otherwise the booost would be cancelled

Possible to do that it chooses Key over armor type? So if armortype is cloth, but a hunter has the key, he will be proiretized in the queue as he has the key. He would then sign up in both the role and key.

Current solution is to add him the armor role just for this signup, or manually book it.

**Comment by iElsha** [comment]
> Current solution is to add him the armor role just for this signup, or manually book it.

We will keep that for now
