### ISSUE TITLE
Precious sending mail information to designated GC

### ISSUE THREAD

**Issue by FyneIcc** [Icecrown-Community/Icecrown-Precious-Bot-Public#60]
When posting a manual !submit and adding GC to note, can Precious then also just send the mailinfo auto to GC assigned?
Like a duplicate to GC + submitter. 

[https://prnt.sc/11caga7](url)

**Comment by Dejnaa** [comment]
THis would be soooo helpful

**Comment by Choppaaz** [comment]
I believe it would be great, is it possible ?

**Comment by iElsha** [comment]
!paymentinfo <runId>

**Comment by iElsha** [comment]
This will only work for M+/PvP runs, not raid as the website is already doing it.

**Comment by iElsha** [comment]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/38140638/128573812-1b3f1acf-dc3b-404a-83d0-838e37cae230.png">
