### ISSUE TITLE
Precious mailing string - doesnt show the faction

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/Icecrown-Precious-Bot-Public#62]
I just realised, if we submit with bot, we don't get the "**faction paid**" in the precious mailing string.

This is how the _**manual submit looks like**_ :
![image](https://user-images.githubusercontent.com/77633500/115238766-57db1b00-a11e-11eb-91bc-1b135223fdff.png)

This is how the _**bot submit looks like**_:
![image](https://user-images.githubusercontent.com/77633500/115239251-d041dc00-a11e-11eb-9d65-a83f58525de1.png)

Would be nice if the bot shows aswell, sometimes i get weird realms, and when i send every mail at once, i'll not realise that for example 1 burninglegion out of 7 will be on alliance - _who plays burninglegion on alliance anyway_

**Comment by Wanhedaa** [comment]
bump

**Comment by iElsha** [comment]
This will be fixed in the coming M+ update
