### ISSUE TITLE
Teams re-work

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#64]
Currently the team system is built around the "Team [H]/Team [A]" and a named team role. With this proposal, this would remain the same, but with the addition of a "Team Leader" role. This is a single, non-named role.

### Team add command
The purpose of the Team Leader role would be to allow them to control who is in and out of their current team, removing the need for admin intervention, and can be controlled like the special pseudo list, so that admins can easily fetch team information. Commands for such a thing might look like this:
!teamadd
!teamremove
e.g: !teamadd @indigo-ragnaros
Which would add the "Team [H]" (dictated by faction of payment char if possible, if done by base role of Alliance/Horde or M+ faction roles, those with both may have problems), and the named team role of the team leader. Only the team leader can invoke this command, anyone else who would be playing with those roles (manually) would be admin or Val'kyr anyway, so no additional roles need permission to use it.

### Signup change
The team leader also has extra responsibility with signups, and should be present in every team-take with the bot, which means the team leader should be able to push the team to the front of the booster queue with the single click. Previous functionality of team take should still exist, in case the leader is not available but 4 members wish to sign up all the same. The issue with this, is knowing who to submit balance to if a single person takes the run, which can be countered with an additional signup step:
![image](https://user-images.githubusercontent.com/43845551/115615074-607e4d80-a2e6-11eb-876b-42f397476394.png)
At this stage, as the team leader has pressed the teamclaim emoji, that single leader is sent the cofirmation from Precious of who to whisper and which voice channel to join with the boost ID. The team players who then run the key simply need to press the last emoji (teamplayer) to fill the run, and once 4 members are inside the run automatically locks with no intervention needed from the advertiser, and goes to ☑️/❌ state:
![image](https://user-images.githubusercontent.com/43845551/115615443-e39fa380-a2e6-11eb-8a58-72cc36d54727.png)
It's important to note, that this extra step can be open perpetually until the team fills the list. If they do not, the advertiser can't submit, but it means the team can snipe a run (or multirun), boost it first, then come back to the boost listing and fill the members between them (which may be several hours later, but the responsibility is theirs to ensure they do. If approaching the 24-hour mark, the advertiser should be able to forcibly 🔒 the run, and missing members will simply miss the balance too, and the run be split among the others. The team can of course have this fixed later in tickets, but it means the advertiser can move on without waiting for the team to fix the signups.

### Default channel posting
Currently all keys post in the M+ section, I simply propose that any keys posted at +16 or higher (and we have them added to the form/site) be posted in the team announcements channel, with a single reaction that the teams can use with the conventions above; team leader can snipe it, or 4x members can click it to fill.
![image](https://user-images.githubusercontent.com/43845551/115616853-97edf980-a2e8-11eb-9d8c-ae42f5badde8.png)

### Role monitoring
Teams don't have any tracking or way for us to know how many runs they have done per cycle, a way to track that via the database would be great, but with or without that addition, there should be a requirement for teams to take/boost at least X amount of keys over a certain amount of cycles to keep the roles, else they are simply removed. This will help with role bloat and will motivate teams to boost at least the minimum requirement to keep their role, which is potentially more team takes than we have now. We can use the data from knowing which teams boost to also run a competition for teams also, if we ever choose to go that direction. We would have to ensure that avertisers use the correct submit m+t for manual team submits for this also.

### Low team boosting
A common request from team candidates is to be able to boost without reaching max requirement, for the purpose of taking keys with the bot only, and not from the team announcement channel. I think this would be done with new roles:
Rare Team - Bot signup access only (no team channel)
Epic Team - All access
Legendary Team - All access, keeps roles through seasons (drops one lower each time)

The requirement for the Rare Teams would be linked to Raider.io teams, as it's a solid indicator that the team are playing together for the keys they have run; it could be as simple as getting the highest epic rank requirement for a solo booster (currently 1700), while as a formally named team on Raider.io.

**Comment by Tueri** [comment]
Update from recent meeting, that "Low" team boosting may also have requirement to be able to cater to at least one armor stack to be eligible.

**Comment by Tueri** [comment]
Another possible enhancement to this would be that Legendary team members can be part of more than one team (2 max should be fine).

**Comment by iElsha** [comment]
You can be part of as many team as you want but can only lead one

**Comment by iElsha** [comment]
Implemented in PvP bot update

**Comment by iElsha** [comment]
https://github.com/iElsha/Icecrown-Precious/pull/53
