### ISSUE TITLE
Submitting with incorrect realm names

### ISSUE THREAD

**Issue by ScroogeD2** [Icecrown-Community/Icecrown-Precious-Bot-Public#66]
Currently, if you type the realm name wrong in a manual submit, the bot tries to figure the correct realm based on the beginning of the string. For example, submitting to the realm "Hello" will be interpreted as "Hellfire"

When submitting to russian realms, you have to use the english realm names instead of the russian ones (Howling Fjord and Soulflayer vs Ревущийфьорд and СвежевательДуш). If you use СвежевательДуш in your submit, the bot will interpret it as Aegwynn, which is fairly easy to miss if you don't take a closer look at the mail data or the submit channel embed.

This is due to user error of course, but still, it'd be nice if an incorrect realm canceled the submit instead of potentially submitting to the wrong realm.

**Comment by iElsha** [comment]
This will be fixed with the new update
