### ISSUE TITLE
Run IDs in manual submits

### ISSUE THREAD

**Issue by ScroogeD2** [Icecrown-Community/Icecrown-Precious-Bot-Public#67]
The runs posted with the bot have their run ID (message ID) visible at the bottom of the embed. 
![image](https://user-images.githubusercontent.com/59540908/118073566-c4aba300-b3b4-11eb-8ea1-60f5802f85cc.png)

Could this be added to manually submitted runs as well? Those currently don't display any useful information in the footer, and it'd save one or two seconds every time you need to check the message ID. Also, it'd make searching for manually submitted runs by ID as easy as it is for bot-submitted ones (in case :papaface: appears in your DMs and gives you an ID and you need to spend some time refreshing your memory about what happened with that specific run).
![image](https://user-images.githubusercontent.com/59540908/118073533-b067a600-b3b4-11eb-9ef6-c79839b368a7.png)

**Comment by iElsha** [comment]
What would be the use case for having the ID in the footer on these msg basically? I don't get it exactly

**Comment by Tueri** [comment]
It makes the run searchable in Discord from DM/Database, I would also like this feature from a management perspective 😄.

Use case from our side is when someone is disputing logs and cannot verify amounts Discord side and Logs side, so we have to search the ID's to find which one is a mismatch, then find what happened to the pot or booster numbers etc.
I know we maybe get 1-2 tickets about it per month, but the only other way is reverse searching by booster ID instead, which isn't productive.

Advertiser side it's just QoL and helps with matching runs to DM or when a booster is chasing them asking them if they submitted with bot vs manual etc.

**Comment by iElsha** [comment]
https://github.com/iElsha/Icecrown-Precious/pull/53
