### ISSUE TITLE
Precious - No RunID for the boosters

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/Icecrown-Precious-Bot-Public#69]
![image](https://user-images.githubusercontent.com/77633500/118728665-dd90da00-b834-11eb-8478-b45a09993109.png)
Once you are selected to a boost, you get this message. But when it's done, you might have to scroll a lot to find the run where you joined - Especially on Tuesdays, where the keys are spamming..

If i remember correctly, old Precious gave us RunID in this message, so we could just klick on the runid to find the run and notify the advertiser about we are done.

**Comment by Tueri** [comment]
![image](https://user-images.githubusercontent.com/43845551/118730586-c8657c80-b82f-11eb-920e-767b00711395.png)

**Comment by iElsha** [comment]
Fixed with the M+ update
