### ISSUE TITLE
Having 2 Trainee ranks

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/Icecrown-Precious-Bot-Public#75]
Hello Elsha, as requested here is the post:

Proposed change:
Make 1 new role called Advertiser Trainee (S1) = Session 0-1.
And change the current Advertiser Trainee to Advertiser Trainee (S2) = Session 2 completed. This role will be able to see and claim the tickets as it does now.

Both should be able to use the M+ bot, and have the same cut %

**Comment by DruidEmmaNielsen** [comment]
Good Idea, But Boring names! 

Adv Trainee Student
Adv Trainee Intern 

:poggies:

**Comment by Teleena** [comment]
Having looked into this some more, the way I intend to change the training program's structure, this likely will be unnecessary as the topics the tickets usually have demand for will both be included in S1.

**Comment by Dejnaa** [comment]
THis has been solved so closing
