### ISSUE TITLE
[PvP] Default unique permissions for poster of boost from website

### ISSUE THREAD

**Issue by FyneIcc** [Icecrown-Community/Icecrown-Precious-Bot-Public#78]
Give poster of a boostannounce the unique permission to see the channel by default -while having all other advertisers not able to see it.
Basically like we have for normal tickets -but also for channels made by posting boost directly from website.

**Comment by iElsha** [comment]
Didn't we said that this might be interesting for other advertiser to know what's happening?

if not, @Tueri, would that be good to have this behaviour for M+ too?

**Comment by Tueri** [comment]
This would be good behaviour, prevents white pings and unnecessary information. If they have booser roles they will be pinged, else they don't need to see it imo.

**Comment by iElsha** [comment]
Will change it for all runs then

**Comment by iElsha** [comment]
Will be deployed today
