### ISSUE TITLE
1,600 vs 2100

### ISSUE THREAD

**Issue by FyneIcc** [Icecrown-Community/Icecrown-Precious-Bot-Public#81]
![image](https://user-images.githubusercontent.com/77837483/125128409-4c383880-e0fe-11eb-90c5-f5477bc3c2af.png)

**Comment by Dejnaa** [comment]
@Bgabor997 would it take much to fix that no other symbols except for 1-0 can be entered to the Rating fields?
Also that it removes 0 if we write 1-9 after it at the start. For example 01600

**Comment by Bgabor997** [comment]
30min for the change, and test edit

**Comment by Dejnaa** [comment]
@iElsha plox approve

**Comment by iElsha** [comment]
it already is

**Comment by Efthymios-Papakostopoulos** [comment]
It's a minor visual issue. Guess if Gabor has some really really spare time can fix that quick. It's a high priority as we speak

**Comment by iElsha** [comment]
I had a check and it seems to be buggy here as we are converting it with commas

**Comment by iElsha** [comment]
Seems to be fixed I forgot to reference the commit, reopen if it's not the case 
![image](https://user-images.githubusercontent.com/38140638/132103168-ce42eb16-1e55-4383-b976-7e15d0298eac.png)
