### ISSUE TITLE
Pin the BaseRun message when posting it.

### ISSUE THREAD

**Issue by FyneIcc** [Icecrown-Community/Icecrown-Precious-Bot-Public#82]
Having to scroll for ages, i can only imagine it's something hindering the boosters claiming too having to scroll so far up when tickets is getting long.

a browsechannel, like RBGannounce, still not an option @ICCDesi ?

https://gyazo.com/bd6d47df71baf097df91b398431e8818

**Comment by Efthymios-Papakostopoulos** [comment]
We might want to change the system a bit. Indeed you have to scroll a lot to find the useful information.

Maybe @iElsha has to suggest something

**Comment by Dejnaa** [comment]
Maybe Pin the Bot Announcements so people can check pin and click on it to get to the top/other bot-posts in the ticket? :)

**Comment by iElsha** [comment]
Will pin the post
