### ISSUE TITLE
Just my daily dose of useless spam from Precious

### ISSUE THREAD

**Issue by FyneIcc** [Icecrown-Community/Icecrown-Precious-Bot-Public#83]
![image](https://user-images.githubusercontent.com/77837483/125132503-afc56480-e104-11eb-9b83-4ea1a5ec336a.png)

Can it be removed for PvP?

**Comment by FyneIcc** [comment]
![image](https://user-images.githubusercontent.com/77837483/125133662-75f55d80-e106-11eb-9935-f3258a0dc82b.png)

Boosters wondering whats wrong aswell

**Comment by LorisBerthelot45** [comment]
![image](https://user-images.githubusercontent.com/25684007/125139087-2d42a200-e110-11eb-83a4-b82c232154d6.png)

**Comment by FyneIcc** [comment]
We got rank1 blizzcon champions getting confused and annoyed by the useless spam by Precious.

They just press random reactions cuz of Precious making a mess.

Yeet the messages 👎 

![Screenshot_20210711-235728_Discord](https://user-images.githubusercontent.com/77837483/125211075-01582580-e2a4-11eb-9c37-cbd955c123a8.jpg)

**Comment by FyneIcc** [comment]
@iElsha

**Comment by FyneIcc** [comment]
Stfu Precioua

https://user-images.githubusercontent.com/77837483/125689639-c3df4bfd-c8ff-4b3c-ac72-5ce90f0fecda.mp4

**Comment by FyneIcc** [comment]
![image](https://user-images.githubusercontent.com/77837483/125987968-295bb16d-e58a-4111-a3fc-5f7dda5435e6.png)

**Comment by FyneIcc** [comment]
![image](https://user-images.githubusercontent.com/77837483/126201627-d4fca080-e923-42e5-88b5-009754cc4cc4.png)

**Comment by iElsha** [comment]
@FyneIcc we were aware of this when releasing PvP it was a pitfall due to the short deadline I had.

It is planned to improve it though

**Comment by iElsha** [comment]
Can you propose an improvement plan for this feature.

I can lower the reminder to once each X days instead but I still want to keep it.

Or remove it when it's running is possible (still each X days seems important though)

**Comment by FyneIcc** [comment]
I think just removing it is fine., our pvpsupport has 11000% control over tickets,(when manage channel permission is granted) running completed and not yet claimed.
They are doing fantastic team keeping track, not just their own tickets.

we dont need a reminder. We never needed when precious wasnt a thing for us. Not an enhancement we wanted.

**Comment by iElsha** [comment]
Will remove for PvP then

**Comment by iElsha** [comment]
The change will be deployed today
