### ISSUE TITLE
Change of format

### ISSUE THREAD

**Issue by FyneIcc** [Icecrown-Community/Icecrown-Precious-Bot-Public#84]
Can we just remove the text? 
Current rating and Desired rating doesnt look good imho.

just do xxxx -> xxxx is clean and smooth 

![image](https://user-images.githubusercontent.com/77837483/125133394-1b5c0180-e106-11eb-8134-cebe75d2112f.png)

**Comment by iElsha** [comment]
What happens for : 
- Wins
- Coaching
- Hire a booster

**Comment by FyneIcc** [comment]
* Wins 
''Boost'' becomes ''Wins'', within the red rectangle it should say how many wins purchased.

* Coaching and Hire a booster 
''Boost'' becomes ''Coaching''/''Hire a booster'', within the red rectangle it should just say ''current rating'', by that i mean just the digits. no need for any letters and words.

**Comment by iElsha** [comment]
> Wins
''Boost'' becomes ''Wins'', within the red rectangle it should say how many wins purchased.

Do you still say the current rating?

> Coaching and Hire a booster
''Boost'' becomes ''Coaching''/''Hire a booster'', within the red rectangle it should just say ''current rating'', by that i mean just the digits. no need for any letters and words.

You're not giving the customer request (2 hours, 1 hour...) anymore, right?

**Comment by FyneIcc** [comment]
Current rating is important indeed.

Not sure what you mean with the 2nd question.
We do still offer hourly purchase.

**Comment by iElsha** [comment]
> Not sure what you mean with the 2nd question.
We do still offer hourly purchase.

In the answer you gave the implementation would result in
Field Name: "Boost"
Field value: XXXX

With this, we are loosing the customer request which is I want X hours of Coaching/Hire a booster. Is that intended to loose this information? If not, can you let me know if the current format (field value) for these boost types is correct? If not, suggest an improvement please.

**Comment by FyneIcc** [comment]
We need to know the clients CR, and how many hours purchased.
I just don't like the aesthetic of all the uneeded text.

**Comment by iElsha** [comment]
It's just aesthetic changes, not a prio except if it impacts pvp support

**Comment by iElsha** [comment]
I'll be declining the feature, I started to make a change but it's really to minor and the change haven't been scoped properly on the impact. Feel free to reopen if you want it to be done.

In that case specify

```
case "Rating":
                field = ""
                value = ""
case "Win":
                field = ""
                value = ""
case "Coaching":
                field = ""
                value = ""
case "Hire a booster":
                field = ""
                value = ""
```
