### ISSUE TITLE
[PvP] :fail: and :delete: papaface

### ISSUE THREAD

**Issue by FyneIcc** [Icecrown-Community/Icecrown-Precious-Bot-Public#86]
@iElsha 

:fail: and :delete: should be removed reaction from everyone but pvpsupport.

When a booster pressed it , it just deleted the channel having us to find client, and digging up ticket transcript.

![Screenshot_20210713-200909_Discord](https://user-images.githubusercontent.com/77837483/125504044-d8fac7ad-ba62-4793-9f63-fc85eb085b1c.jpg)

Isnt it ment that if booster clicks it, it notifies advertiser its a failed run, and they should unlock it. Then either find new booster or refund. Not just delete the ticket.

**Comment by FyneIcc** [comment]
Actually, advertisers can probably learn to use it properly

When boosters clicks it, it ONLY sends notification to advertiser -who then has permission to actually delete it. 
Boosters are getting anxious about Precious telling them to ASAP click something DMs.

**Comment by FyneIcc** [comment]
update;

PvPSupport will be instructed to manually remove :fail: reaction in every post by Precious. Removing the possibility of miss-use entirely, but we would love to have permanent change of only pvpsupport able to press :fail:
We're getting to many tickets mistakenly closed.

**Comment by iElsha** [comment]
Boosters can not close the channel on clicking on the fail, or success emoji. This is not possible.

Tickets boosts can not be deleted by advertiser when marking it as submitted or fail.

Only non-ticket boosts can be, and this is only possible by advertiser.

**Comment by iElsha** [comment]
Closing the ticket as it seems invalid, reopen if needed
