### ISSUE TITLE
Help us help them!

### ISSUE THREAD

**Issue by HexyICC** [Icecrown-Community/Icecrown-Precious-Bot-Public#87]
Could we please get a Dropdown Box with Advertisers name so we do not have to get them to submit manually.

![Capture](https://user-images.githubusercontent.com/87047665/125992778-32d85532-b825-435e-96fb-bc637354319f.JPG)

**Comment by Bgabor997** [comment]
i know i said it, but i guess a select is too much, bcs we have a lot of advertisers, but an input for advertiser ID is definetly doable

**Comment by momos-icc** [comment]
Couldn't we do something with the Discord Tag similar to how we do it with customers? :D

**Comment by Bgabor997** [comment]
discord ID would be easier for me xD but ofc, i can figure out something

**Comment by momos-icc** [comment]
Either is fine for me but getting Momos#0001 is "easier" than getting the ID if you're on mobile for example

**Comment by Bgabor997** [comment]
will look for a solution after my raid ^^

**Comment by iElsha** [comment]
Advs have access to the form now is it still needed?

**Comment by iElsha** [comment]
On top of that the idea is declined as it involves some privacy issues.

**Comment by FyneIcc** [comment]
> Advs have access to the form now is it still needed?

No, its all good now since its open for em.
