### ISSUE TITLE
URGENT Team Take (PVP BOT)

### ISSUE THREAD

**Issue by HexyICC** [Icecrown-Community/Icecrown-Precious-Bot-Public#88]
Please can we get a "Team Take" Emoji that will give the booster both of the spots, not always both of the boosters are either in Discord or both at the PC at the same time to sign up for a boost, alot of us as booster would want to do boosts with our partners we have played with before, in nova this happens where 2 random boosters will sign and take a boost, this is horrific and never ends well as you have no synergy with the other boosters as you have never played with them before.

![image](https://user-images.githubusercontent.com/87047665/125993331-8d513a62-5f0b-4dcc-8246-ff3128b3c15a.png)

**Comment by FyneIcc** [comment]
I do agree with you, but i also kind of want all boosters to be in the discord. This ensures the quality we require to boost for IcecrownCommunity.
You, Hexy, as an example i trust to bring in a decent human being, and at a minimum good player. I can easily put you also accountable if anything bad happens.

Others i find hard to trust ''i can take this with my partner, he is really good''.
Next thing you know his friend is a fucking pepega acting up and sperging out. Yes this has happen handful of times.
There is a reason we have application system.

BUUUUT I do believe we can make both of us happy.
Team-claim and enforce all boosters to be part of community. 
You want the team-claim mainly so the 2nd position wont get taken by someone els you don't want to play with. 
This kind of makes it awkward to sit and wait for your partner to signup and tell the random booster to unclaim.

If we have :pvp1: , :pvp2:, and also :pvptc: for team-claim as suggested by you. But if the partner signing up with original booster want payment he will have to join discord and be accepted through application form.
Or just a fast check-pvp.fr link to me to speed it up.

Or we can do the lazy way and just blindly accept the inhousevouch, and deal with possible pepegas again.

**Comment by momos-icc** [comment]
_"Or we can do the lazy way and just blindly accept the inhousevouch, and deal with possible pepegas again."_

If we go this route just let the boosters know they are responsible for the person they bring and if they cause issues they're liable to a strike/balance removal/etc. Then they'd hopefully be more likely to encourage their friend to get roles so they don't have to be on the line for their mistakes 👀

**Comment by iElsha** [comment]
I personally don't agree for the quality purpose reason. We have an higher quality requirement than the mentioned community above.

This is a no go for me, my colleagues can contradict me if needed. In that case I let fyne escalate the issue. Closing for now.
