### ISSUE TITLE
Request "manage channels" permission on PvP Support role 

### ISSUE THREAD

**Issue by FyneIcc** [Icecrown-Community/Icecrown-Precious-Bot-Public#89]
This is so we can edit the channel names to our initials, making it a lot easier to keep track of who handles what.
Also if we need to manually close the channel without the use of emotes.

**Comment by iElsha** [comment]
> Also if we need to manually close the channel without the use of emotes

You should always use emojis for closing channels

Giving permission for editing channels names is a bit overkilled, maybe a command could be enough as the bot will always override your change on each new step

**Comment by FyneIcc** [comment]
So u want us to ping management to close tickets that's not being claimed, sounds like a lot of pings? We cannot close channels,  only the poster of the ticket can close it, and very often the advertiser is AFK or not able to reach. Sure we can keep tickets open, but im aware Dejna and Tueri hates tickets left alone for long periods of time.

> maybe a command could be enough

if it renames the ticket name to peoples initials, sure!

**Comment by iElsha** [comment]
A command - we agreed on it on Discord

**Comment by iElsha** [comment]
I'm changing my mind, a command is not the right choice, I grant you the "manage_channel" permission instead for handling them.
<img width="432" alt="image" src="https://user-images.githubusercontent.com/38140638/128627881-d78ce704-3148-4bcd-a3ef-ebd02bf0908a.png">

Regarding the channel name - can you open a new issue about it and describe what would be the format you'd like to have for PvP runs?

**Comment by FyneIcc** [comment]
> I grant you the "manage_channel" permission instead for handling them. 

Do you mean me, Fyne, or all PvPsupport ? 

> Regarding the channel name - can you open a new issue about it and describe what would be the format you'd like to have for PvP runs? 

We just edit the name with our initials in it. We dont delete anything really.

Orrrrr do you mean the other issue about formating?
https://github.com/Icecrown-Community/Icecrown-Precious-Bot-Public/issues/84

**Comment by iElsha** [comment]
For PvP Support

--
No I mean what's the format of the channel name you'd like for PvP instead of the current one?
<img width="231" alt="image" src="https://user-images.githubusercontent.com/38140638/128630365-6bfa069c-921c-4a31-87c1-d82f9d02d92e.png">

**Comment by iElsha** [comment]
The change will be deployed today

**Comment by FyneIcc** [comment]
Its fine the way it is :)
