### ISSUE TITLE
baiter channel names

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/Icecrown-Precious-Bot-Public#92]
Someone posted 4x random keys, but the channel name was "nostack-2xanyrkey..." 

so we just saw 2x key for the first time, then we had to read it is a 4x keys boost. 
"yeeah read the note blah blah blah" but i think it should be "nostack-4xanyrkey"  instead of "nostack-2xanyrkey_2xanyrkey"

![image](https://user-images.githubusercontent.com/77633500/127311440-7b15e41f-6043-455d-82be-9cef40ba41a4.png)

**Comment by iElsha** [comment]
This is not a bug, most likely the advertiser put 2 keys in the form that were the same and select 1/3, 2/2, 3/1 runs for them, in that case it's the normal behavior

**Comment by iElsha** [comment]
Just checked the log and database, run has been created with 2x2 Random key, this is not a bug.
