### ISSUE TITLE
PvP Channels and their "Slow Modes" are frustrating for the Clients.

### ISSUE THREAD

**Issue by DruidEmmaNielsen** [Icecrown-Community/Icecrown-Precious-Bot-Public#93]
To begin with, sorry if wrong department, a bit unsure where pvp goes. 

To the case:  There is currently a minut long slow mode on channels, I've no idea why when the channels are already isolated away from everyone. 

The clients then decides to DM the boosters instead, and then the conversations are away from the channel. 
So i do not exactly know the purpose you guys want on the channel, but currently it is shoo'ing clients away from them instead.

I don't personally see the reason of why a slowmode exists.

**Comment by Tueri** [comment]
This works well in the M+ section but in practice is not good for the PvP department. I agree - remove it.

**Comment by iElsha** [comment]
Done in https://github.com/iElsha/Icecrown-Precious/pull/69
