### ISSUE TITLE
Post 24Hr submit notification spamming DM's

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#99]
When an advertiser hasn't submitted a run for 24 hours, both the advertiser and the boosters get their DM's flooded by Precious, at a rate of about 1-2 messages per second for the adv, half as much for the boosters.
![image](https://user-images.githubusercontent.com/43845551/131199995-8d2cf896-803d-4616-a9cc-6202bd4d4462.png)
![image](https://user-images.githubusercontent.com/43845551/131200018-aa69c025-f532-43d5-9725-407c07dbb3ee.png)

**Comment by iElsha** [comment]
Fixed in https://github.com/iElsha/Icecrown-Precious/pull/75
